### ISSUE TITLE
setRawMode is not a function?

### ISSUE THREAD

**Issue by AquiGorka** [mafintosh/tetris#4]
User at nbba-gludlow in ~/tetris (master●)
$ node index.js
 tetris 0.1.6 by @mafintosh

C:\Users\User\.babun\cygwin\home\User\tetris\index.js:333
        require('tty').setRawMode(true);
                       ^
TypeError: require(...).setRawMode is not a function
    at Object.<anonymous> (C:\Users\User\.babun\cygwin\home\User\tetris\index.js:333:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

(yes, I'm at work and using windows + babun)

**Comment by dillonko** [comment]
Yeah I love this game The solutions is the following below. but I think the key board interactions a are not working:
```js
try {
        process.stdin.setRawMode(true);
} catch (err) {
        if(process.stdin.isTTY){
                process.stdin.setRawMode(true);
        }
}

````
